services:
  blogify.api:
    image: ${DOCKER_REGISTRY-}blogifyapi
    build:
      context: .
      dockerfile: Blogify.Api/Dockerfile
      
  blogify-db:
    image: postgres:latest
    container_name: blogify.Db
    environment:
      - POSTGRES_DB=blogify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  blogify-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: Blogify.Identity
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files/blogify-realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - 18080:8080
  
  blogify-seq:
    image: datalust/seq:latest
    container_name: Blogify.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  blogify-redis:
    image: redis:latest
    container_name: Blogify.Redis
    restart: always
    ports:
      - '6379:6379'